// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    // Guard: supabase may be null when running without backend credentials
    const authApi = (supabase as unknown as { auth?: { getSession?: () => Promise<{ data: { session: { access_token?: string } | null } }> } }).auth;
    const token = authApi?.getSession
      ? await authApi.getSession().then((r) => r.data.session?.access_token).catch(() => undefined)
      : undefined;
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
