/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicantsRouteImport } from './routes/admin.applicants'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminEssRouteImport } from './routes/admin.ess'
import { Route as AdminHcmRouteImport } from './routes/admin.hcm'
import { Route as AdminOnboardingRouteImport } from './routes/admin.onboarding'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminRecruitmentRouteImport } from './routes/admin.recruitment'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as EmployeeIndexRouteImport } from './routes/employee.index'
import { Route as EmployeeEssRouteImport } from './routes/employee.ess'
import { Route as EmployeeOnboardingRouteImport } from './routes/employee.onboarding'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeSettingsRouteImport } from './routes/employee.settings'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as SuperadminApplicantsRouteImport } from './routes/superadmin.applicants'
import { Route as SuperadminAuditRouteImport } from './routes/superadmin.audit'
import { Route as SuperadminEmployeesRouteImport } from './routes/superadmin.employees'
import { Route as SuperadminEssRouteImport } from './routes/superadmin.ess'
import { Route as SuperadminHcmRouteImport } from './routes/superadmin.hcm'
import { Route as SuperadminOnboardingRouteImport } from './routes/superadmin.onboarding'
import { Route as SuperadminProfileRouteImport } from './routes/superadmin.profile'
import { Route as SuperadminRecruitmentRouteImport } from './routes/superadmin.recruitment'
import { Route as SuperadminSettingsRouteImport } from './routes/superadmin.settings'
import { Route as SuperadminUsersRouteImport } from './routes/superadmin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicantsRoute = AdminApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEssRoute = AdminEssRouteImport.update({
  id: '/ess',
  path: '/ess',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHcmRoute = AdminHcmRouteImport.update({
  id: '/hcm',
  path: '/hcm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOnboardingRoute = AdminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecruitmentRoute = AdminRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeEssRoute = EmployeeEssRouteImport.update({
  id: '/ess',
  path: '/ess',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeOnboardingRoute = EmployeeOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSettingsRoute = EmployeeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => EmployeeRoute,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminApplicantsRoute = SuperadminApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAuditRoute = SuperadminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminEmployeesRoute = SuperadminEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminEssRoute = SuperadminEssRouteImport.update({
  id: '/ess',
  path: '/ess',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminHcmRoute = SuperadminHcmRouteImport.update({
  id: '/hcm',
  path: '/hcm',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminOnboardingRoute = SuperadminOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminProfileRoute = SuperadminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminRecruitmentRoute = SuperadminRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminSettingsRoute = SuperadminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminUsersRoute = SuperadminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperadminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/ess': typeof AdminEssRoute
  '/admin/hcm': typeof AdminHcmRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/ess': typeof EmployeeEssRoute
  '/employee/onboarding': typeof EmployeeOnboardingRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/superadmin/applicants': typeof SuperadminApplicantsRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/employees': typeof SuperadminEmployeesRoute
  '/superadmin/ess': typeof SuperadminEssRoute
  '/superadmin/hcm': typeof SuperadminHcmRoute
  '/superadmin/onboarding': typeof SuperadminOnboardingRoute
  '/superadmin/profile': typeof SuperadminProfileRoute
  '/superadmin/recruitment': typeof SuperadminRecruitmentRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/ess': typeof AdminEssRoute
  '/admin/hcm': typeof AdminHcmRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/ess': typeof EmployeeEssRoute
  '/employee/onboarding': typeof EmployeeOnboardingRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/superadmin/applicants': typeof SuperadminApplicantsRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/employees': typeof SuperadminEmployeesRoute
  '/superadmin/ess': typeof SuperadminEssRoute
  '/superadmin/hcm': typeof SuperadminHcmRoute
  '/superadmin/onboarding': typeof SuperadminOnboardingRoute
  '/superadmin/profile': typeof SuperadminProfileRoute
  '/superadmin/recruitment': typeof SuperadminRecruitmentRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/employee': typeof EmployeeIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/employee': typeof EmployeeRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/otp': typeof OtpRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/admin/applicants': typeof AdminApplicantsRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/ess': typeof AdminEssRoute
  '/admin/hcm': typeof AdminHcmRoute
  '/admin/onboarding': typeof AdminOnboardingRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recruitment': typeof AdminRecruitmentRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/employee/ess': typeof EmployeeEssRoute
  '/employee/onboarding': typeof EmployeeOnboardingRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/employee/settings': typeof EmployeeSettingsRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/superadmin/applicants': typeof SuperadminApplicantsRoute
  '/superadmin/audit': typeof SuperadminAuditRoute
  '/superadmin/employees': typeof SuperadminEmployeesRoute
  '/superadmin/ess': typeof SuperadminEssRoute
  '/superadmin/hcm': typeof SuperadminHcmRoute
  '/superadmin/onboarding': typeof SuperadminOnboardingRoute
  '/superadmin/profile': typeof SuperadminProfileRoute
  '/superadmin/recruitment': typeof SuperadminRecruitmentRoute
  '/superadmin/settings': typeof SuperadminSettingsRoute
  '/superadmin/users': typeof SuperadminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/employee/': typeof EmployeeIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/employee'
    | '/faq'
    | '/login'
    | '/otp'
    | '/superadmin'
    | '/admin/applicants'
    | '/admin/employees'
    | '/admin/ess'
    | '/admin/hcm'
    | '/admin/onboarding'
    | '/admin/profile'
    | '/admin/recruitment'
    | '/admin/settings'
    | '/employee/ess'
    | '/employee/onboarding'
    | '/employee/profile'
    | '/employee/settings'
    | '/jobs/$jobId'
    | '/superadmin/applicants'
    | '/superadmin/audit'
    | '/superadmin/employees'
    | '/superadmin/ess'
    | '/superadmin/hcm'
    | '/superadmin/onboarding'
    | '/superadmin/profile'
    | '/superadmin/recruitment'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin/'
    | '/employee/'
    | '/jobs/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/login'
    | '/otp'
    | '/admin/applicants'
    | '/admin/employees'
    | '/admin/ess'
    | '/admin/hcm'
    | '/admin/onboarding'
    | '/admin/profile'
    | '/admin/recruitment'
    | '/admin/settings'
    | '/employee/ess'
    | '/employee/onboarding'
    | '/employee/profile'
    | '/employee/settings'
    | '/jobs/$jobId'
    | '/superadmin/applicants'
    | '/superadmin/audit'
    | '/superadmin/employees'
    | '/superadmin/ess'
    | '/superadmin/hcm'
    | '/superadmin/onboarding'
    | '/superadmin/profile'
    | '/superadmin/recruitment'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin'
    | '/employee'
    | '/jobs'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/employee'
    | '/faq'
    | '/login'
    | '/otp'
    | '/superadmin'
    | '/admin/applicants'
    | '/admin/employees'
    | '/admin/ess'
    | '/admin/hcm'
    | '/admin/onboarding'
    | '/admin/profile'
    | '/admin/recruitment'
    | '/admin/settings'
    | '/employee/ess'
    | '/employee/onboarding'
    | '/employee/profile'
    | '/employee/settings'
    | '/jobs/$jobId'
    | '/superadmin/applicants'
    | '/superadmin/audit'
    | '/superadmin/employees'
    | '/superadmin/ess'
    | '/superadmin/hcm'
    | '/superadmin/onboarding'
    | '/superadmin/profile'
    | '/superadmin/recruitment'
    | '/superadmin/settings'
    | '/superadmin/users'
    | '/admin/'
    | '/employee/'
    | '/jobs/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  EmployeeRoute: typeof EmployeeRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  OtpRoute: typeof OtpRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  JobsJobIdRoute: typeof JobsJobIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applicants': {
      id: '/admin/applicants'
      path: '/applicants'
      fullPath: '/admin/applicants'
      preLoaderRoute: typeof AdminApplicantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ess': {
      id: '/admin/ess'
      path: '/ess'
      fullPath: '/admin/ess'
      preLoaderRoute: typeof AdminEssRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hcm': {
      id: '/admin/hcm'
      path: '/hcm'
      fullPath: '/admin/hcm'
      preLoaderRoute: typeof AdminHcmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/onboarding': {
      id: '/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AdminOnboardingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recruitment': {
      id: '/admin/recruitment'
      path: '/recruitment'
      fullPath: '/admin/recruitment'
      preLoaderRoute: typeof AdminRecruitmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/employee/': {
      id: '/employee/'
      path: '/'
      fullPath: '/employee/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/ess': {
      id: '/employee/ess'
      path: '/ess'
      fullPath: '/employee/ess'
      preLoaderRoute: typeof EmployeeEssRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/onboarding': {
      id: '/employee/onboarding'
      path: '/onboarding'
      fullPath: '/employee/onboarding'
      preLoaderRoute: typeof EmployeeOnboardingRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/employee/settings': {
      id: '/employee/settings'
      path: '/settings'
      fullPath: '/employee/settings'
      preLoaderRoute: typeof EmployeeSettingsRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/applicants': {
      id: '/superadmin/applicants'
      path: '/applicants'
      fullPath: '/superadmin/applicants'
      preLoaderRoute: typeof SuperadminApplicantsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/audit': {
      id: '/superadmin/audit'
      path: '/audit'
      fullPath: '/superadmin/audit'
      preLoaderRoute: typeof SuperadminAuditRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/employees': {
      id: '/superadmin/employees'
      path: '/employees'
      fullPath: '/superadmin/employees'
      preLoaderRoute: typeof SuperadminEmployeesRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/ess': {
      id: '/superadmin/ess'
      path: '/ess'
      fullPath: '/superadmin/ess'
      preLoaderRoute: typeof SuperadminEssRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/hcm': {
      id: '/superadmin/hcm'
      path: '/hcm'
      fullPath: '/superadmin/hcm'
      preLoaderRoute: typeof SuperadminHcmRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/onboarding': {
      id: '/superadmin/onboarding'
      path: '/onboarding'
      fullPath: '/superadmin/onboarding'
      preLoaderRoute: typeof SuperadminOnboardingRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/profile': {
      id: '/superadmin/profile'
      path: '/profile'
      fullPath: '/superadmin/profile'
      preLoaderRoute: typeof SuperadminProfileRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/recruitment': {
      id: '/superadmin/recruitment'
      path: '/recruitment'
      fullPath: '/superadmin/recruitment'
      preLoaderRoute: typeof SuperadminRecruitmentRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/settings': {
      id: '/superadmin/settings'
      path: '/settings'
      fullPath: '/superadmin/settings'
      preLoaderRoute: typeof SuperadminSettingsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/users': {
      id: '/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof SuperadminUsersRouteImport
      parentRoute: typeof SuperadminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicantsRoute: typeof AdminApplicantsRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminEssRoute: typeof AdminEssRoute
  AdminHcmRoute: typeof AdminHcmRoute
  AdminOnboardingRoute: typeof AdminOnboardingRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRecruitmentRoute: typeof AdminRecruitmentRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicantsRoute: AdminApplicantsRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminEssRoute: AdminEssRoute,
  AdminHcmRoute: AdminHcmRoute,
  AdminOnboardingRoute: AdminOnboardingRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRecruitmentRoute: AdminRecruitmentRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EmployeeRouteChildren {
  EmployeeEssRoute: typeof EmployeeEssRoute
  EmployeeOnboardingRoute: typeof EmployeeOnboardingRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
  EmployeeSettingsRoute: typeof EmployeeSettingsRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeEssRoute: EmployeeEssRoute,
  EmployeeOnboardingRoute: EmployeeOnboardingRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
  EmployeeSettingsRoute: EmployeeSettingsRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminApplicantsRoute: typeof SuperadminApplicantsRoute
  SuperadminAuditRoute: typeof SuperadminAuditRoute
  SuperadminEmployeesRoute: typeof SuperadminEmployeesRoute
  SuperadminEssRoute: typeof SuperadminEssRoute
  SuperadminHcmRoute: typeof SuperadminHcmRoute
  SuperadminOnboardingRoute: typeof SuperadminOnboardingRoute
  SuperadminProfileRoute: typeof SuperadminProfileRoute
  SuperadminRecruitmentRoute: typeof SuperadminRecruitmentRoute
  SuperadminSettingsRoute: typeof SuperadminSettingsRoute
  SuperadminUsersRoute: typeof SuperadminUsersRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminApplicantsRoute: SuperadminApplicantsRoute,
  SuperadminAuditRoute: SuperadminAuditRoute,
  SuperadminEmployeesRoute: SuperadminEmployeesRoute,
  SuperadminEssRoute: SuperadminEssRoute,
  SuperadminHcmRoute: SuperadminHcmRoute,
  SuperadminOnboardingRoute: SuperadminOnboardingRoute,
  SuperadminProfileRoute: SuperadminProfileRoute,
  SuperadminRecruitmentRoute: SuperadminRecruitmentRoute,
  SuperadminSettingsRoute: SuperadminSettingsRoute,
  SuperadminUsersRoute: SuperadminUsersRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  EmployeeRoute: EmployeeRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  OtpRoute: OtpRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  JobsJobIdRoute: JobsJobIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
